# Generated by Django 2.0 on 2019-08-12 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Businesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessesName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='feeds/')),
                ('post', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=220)),
                ('occupationCount', models.IntegerField()),
                ('police', models.CharField(blank=True, max_length=50)),
                ('hospital', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='profile/')),
                ('location', models.CharField(max_length=50)),
                ('secondaryEmail', models.EmailField(max_length=50)),
                ('neigbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbours.Neighbour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feeds',
            name='neigbor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbours.Neighbour'),
        ),
        migrations.AddField(
            model_name='feeds',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesses',
            name='neigbor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbours.Neighbour'),
        ),
        migrations.AddField(
            model_name='businesses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
